server:
 port: 8082
 context-path: /cityTrading
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/citytrading?useSSL=true
  username: root
  password: 123456
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  